
export const itemsPerPage = 10;

export const plans = {
    'Ad': [
      { name: 'Basic', price: 4.99, credits: 5 },
      { name: 'Standard', price: 8.99, credits: 10 },
      { name: 'Premium', price: 11.99, credits: 15 },
      { name: 'Landing Page Ad', price: 1000, perDayAd: 1 },
      { name: 'Banner Ad', price: 1000, perDayAd: 1 }
    ],
    'Job': [
      { name: 'Basic', price: 2.99, credits: 5 },
      { name: 'Standard', price: 4.99, credits: 10 },
      { name: 'Premium', price: 7.99, credits: 15 }
    ]
  };
export const BASE_APP_URL = 'http://localhost:3000';
//export const BASE_APP_URL = 'https://jobportal-three-mu.vercel.app';

export const BASE_API_URL = 'http://localhost:3001';
//export const BASE_API_URL = 'https://job-portal-api-qzha.onrender.com';

export const CitiesList = ["Alexandra",
    "Arrowtown",
    "Ashburton",
    "Auckland",
    "Balclutha",
    "Blenheim",
    "Bulls",
    "Cambridge",
    "Carterton",
    "Cheviot",
    "Christchurch",
    "Clinton",
    "Clyde",
    "Coromandel",
    "Cromwell",
    "Dargaville",
    "Dunedin",
    "Fairlie",
    "Feilding",
    "Foxton",
    "Geraldine",
    "Gisborne",
    "Greymouth",
    "Haast",
    "Hamilton",
    "Hastings",
    "Havelock North",
    "Hawera",
    "Helensville",
    "Hibiscus Coast",
    "Hokitika",
    "Huntly",
    "Invercargill",
    "Kaikohe",
    "Kaitaia",
    "Katikati",
    "Kawerau",
    "Kawhia",
    "Kerikeri",
    "Kurow",
    "Lawrence",
    "Levin",
    "Lower Hutt",
    "Lumsden",
    "Lyttelton",
    "Marton",
    "Masterton",
    "Matamata",
    "Mosgiel",
    "Napier",
    "Nelson",
    "New Plymouth",
    "Oamaru",
    "Ohaeawai",
    "Opotiki",
    "Otorohanga",
    "Paeroa",
    "Palmerston North",
    "Paraparaumu",
    "Porirua",
    "Pukekohe",
    "Putaruru",
    "Queenstown",
    "Raglan",
    "Ranfurly",
    "Rangiora",
    "Reefton",
    "Richmond",
    "Rolleston",
    "Rotorua",
    "Ruakaka",
    "Stratford",
    "Tairua",
    "Tapanui",
    "Taupō",
    "Tauranga",
    "Te Awamutu",
    "Te Kuiti",
    "Te Puke",
    "Thames",
    "Timaru",
    "Tokoroa",
    "Tuakau",
    "Twizel",
    "Upper Hutt",
    "Waiheke Island",
    "Waihi",
    "Waimate",
    "Waiouru",
    "Waipawa",
    "Wairoa",
    "Wanaka",
    "Warkworth",
    "Wellington",
    "Westport",
    "Whakatāne",
    "Whanganui",
    "Whangārei",
    "Winton",
    "Woodville"
]

export const jobColumns = [
    "Support",
    "Job Title",
    "Job Reference",
    "Posted Date",
    "End Date",
    "Status",
    "Views",
    "Applications",
    "Shortlisted",
    "Actions"
]


export const adColumns = [
    "Support",
    "AD Title",
    "Posted Date",
    "End Date",
    "Status",
    "Views",
    "Actions"
]