import { loadStripe } from "@stripe/stripe-js";

export const itemsPerPage = 10;

export const plans = { "Basic": 2.99, "Standard": 5.99, "Premium": 10.99 };

export const BASE_APP_URL = 'http://localhost:3000';

export const BASE_API_URL = 'http://localhost:8080';

export const stripePromise = loadStripe("pk_test_51PKHdMSIkLQ1QpWMWtk1C0swqVaqjKD661Tk5XyEaEoPDIolQZ3e2Dymp7x0iTvyZrjfQDQSZRB1ju6sUTpyr24d00kzeTZNNY");

export const CitiesList = ["Alexandra",
    "Arrowtown",
    "Ashburton",
    "Auckland",
    "Balclutha",
    "Blenheim",
    "Bulls",
    "Cambridge",
    "Carterton",
    "Cheviot",
    "Christchurch",
    "Clinton",
    "Clyde",
    "Coromandel",
    "Cromwell",
    "Dargaville",
    "Dunedin",
    "Fairlie",
    "Feilding",
    "Foxton",
    "Geraldine",
    "Gisborne",
    "Greymouth",
    "Haast",
    "Hamilton",
    "Hastings",
    "Havelock North",
    "Hawera",
    "Helensville",
    "Hibiscus Coast",
    "Hokitika",
    "Huntly",
    "Invercargill",
    "Kaikohe",
    "Kaitaia",
    "Katikati",
    "Kawerau",
    "Kawhia",
    "Kerikeri",
    "Kurow",
    "Lawrence",
    "Levin",
    "Lower Hutt",
    "Lumsden",
    "Lyttelton",
    "Marton",
    "Masterton",
    "Matamata",
    "Mosgiel",
    "Napier",
    "Nelson",
    "New Plymouth",
    "Oamaru",
    "Ohaeawai",
    "Opotiki",
    "Otorohanga",
    "Paeroa",
    "Palmerston North",
    "Paraparaumu",
    "Porirua",
    "Pukekohe",
    "Putaruru",
    "Queenstown",
    "Raglan",
    "Ranfurly",
    "Rangiora",
    "Reefton",
    "Richmond",
    "Rolleston",
    "Rotorua",
    "Ruakaka",
    "Stratford",
    "Tairua",
    "Tapanui",
    "Taupō",
    "Tauranga",
    "Te Awamutu",
    "Te Kuiti",
    "Te Puke",
    "Thames",
    "Timaru",
    "Tokoroa",
    "Tuakau",
    "Twizel",
    "Upper Hutt",
    "Waiheke Island",
    "Waihi",
    "Waimate",
    "Waiouru",
    "Waipawa",
    "Wairoa",
    "Wanaka",
    "Warkworth",
    "Wellington",
    "Westport",
    "Whakatāne",
    "Whanganui",
    "Whangārei",
    "Winton",
    "Woodville"
]
